CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(50) DEFAULT 'user'
);

CREATE TABLE asignaturas (
    id SERIAL PRIMARY KEY,
    leader_id INTEGER UNIQUE REFERENCES usuarios(id) DEFAULT NULL,
    name VARCHAR(100) NOT NULL,
    year VARCHAR(150) NOT NULL,
    semester VARCHAR(255) NOT NULL,
    C INTEGER DEFAULT NULL, 
    CP INTEGER DEFAULT NULL,
    S INTEGER DEFAULT NULL,
    PL INTEGER DEFAULT NULL,
    TE INTEGER DEFAULT NULL,
    T INTEGER DEFAULT NULL,
    PP INTEGER DEFAULT NULL,
    EC INTEGER DEFAULT NULL,
    TC INTEGER DEFAULT NULL,
    EF INTEGER DEFAULT NULL,
    hours INTEGER NOT NULL,
    date_start TIMESTAMP NOT NULL,
    date_end TIMESTAMP NOT NULL
);
