//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "asignaturas")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub leader_id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub year: String,
    #[sea_orm(column_type = "Text")]
    pub semester: String,
    pub c: Option<i32>,
    pub cp: Option<i32>,
    pub s: Option<i32>,
    pub pl: Option<i32>,
    pub te: Option<i32>,
    pub t: Option<i32>,
    pub pp: Option<i32>,
    pub ec: Option<i32>,
    pub tc: Option<i32>,
    pub ef: Option<i32>,
    pub hours: i32,
    pub date_start: DateTime,
    pub date_end: DateTime,
    pub weeks: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::LeaderId",
        to = "super::usuarios::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usuarios,
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
