//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "asignaturas")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub jefe_id: Option<i32>,
    pub name: String,
    pub year: String,
    pub semester: String,
    pub cp: Option<i32>,
    pub c: Option<i32>,
    pub l: Option<i32>,
    pub t: Option<i32>,
    pub s: Option<i32>,
    pub pp: Option<i32>,
    pub pf: Option<i32>,
    pub hours: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::JefeId",
        to = "super::usuarios::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Usuarios,
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
