//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "balance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub asignatura_id: Option<i32>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::asignaturas::Entity",
        from = "Column::AsignaturaId",
        to = "super::asignaturas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Asignaturas,
}

impl Related<super::asignaturas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Asignaturas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
