//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "balances")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub academic_year: String,
    #[sea_orm(column_type = "Text")]
    pub period: String,
    #[sea_orm(column_type = "Text")]
    pub academic_year_text: String,
    pub start_date: Date,
    pub weeks: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub subjects: Json,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub deadline: Option<Date>,
    pub allow_leader_edit: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub non_academic_periods: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::balance_fragments::Entity")]
    BalanceFragments,
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::UserId",
        to = "super::usuarios::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Usuarios,
}

impl Related<super::balance_fragments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BalanceFragments.def()
    }
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
