//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "balance_fragments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub balance_id: i32,
    pub asignatura_id: i32,
    pub subject_leader_id: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Json,
    pub completed_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::asignaturas::Entity",
        from = "Column::AsignaturaId",
        to = "super::asignaturas::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Asignaturas,
    #[sea_orm(
        belongs_to = "super::balances::Entity",
        from = "Column::BalanceId",
        to = "super::balances::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Balances,
    #[sea_orm(
        belongs_to = "super::usuarios::Entity",
        from = "Column::SubjectLeaderId",
        to = "super::usuarios::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Usuarios,
}

impl Related<super::asignaturas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Asignaturas.def()
    }
}

impl Related<super::balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Balances.def()
    }
}

impl Related<super::usuarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
