//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod asignaturas;
pub mod audit_logs;
pub mod balance_fragments;
pub mod balances;
pub mod schema_migrations;
pub mod system_settings;
pub mod usuarios;
