//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::asignaturas::Entity as Asignaturas;
pub use super::audit_logs::Entity as AuditLogs;
pub use super::balance_fragments::Entity as BalanceFragments;
pub use super::balances::Entity as Balances;
pub use super::usuarios::Entity as Usuarios;
