//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "usuarios")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub token: String,
    pub created_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub role: Option<String>,
    #[sea_orm(column_type = "Text", unique)]
    pub user_name: String,
    pub must_change_password: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::asignaturas::Entity")]
    Asignaturas,
    #[sea_orm(has_many = "super::audit_logs::Entity")]
    AuditLogs,
    #[sea_orm(has_many = "super::balance_fragments::Entity")]
    BalanceFragments,
    #[sea_orm(has_many = "super::balances::Entity")]
    Balances,
}

impl Related<super::asignaturas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Asignaturas.def()
    }
}

impl Related<super::audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLogs.def()
    }
}

impl Related<super::balance_fragments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BalanceFragments.def()
    }
}

impl Related<super::balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Balances.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
